version: "3.1"

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    env_file:
      - .env
    ports:
      - "5050:80"

  fastapi:
    build: .
    #image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8888:8000"

#   mysql_db:
#     image: mysql
#     ports:
#       - "3306:3306"
#     volumes:
#       - db_data:/var/lib/mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: 123456
#       MYSQL_DATABASE: readings
#       MYSQL_USER: diabetic
#       MYSQL_PASSWORD: diabetic

volumes:
  db_data: {}
