version: "3.2"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
      - ./database_setup/mongo_setup/mongod.conf:/etc/mongo/mongod.conf  # Mount the config file
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]  # Tell MongoDB to use the
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mynetwork

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${ME_CONFIG_MONGODB_ADMINUSERNAME}:${ME_CONFIG_MONGODB_ADMINPASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - mynetwork

  postgresql_db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - postgresql_volume:/var/lib/postgresql/data
      - ./database_setup/postgresql_setup/postgresql.conf:/etc/postgresql/postgresql.conf  # Mount config
      - ./database_setup/postgresql_setup:/docker-entrypoint-initdb.d  # Mount SQL scripts here

    command:  ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]  # Use the custom config file
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    depends_on: 
      - postgresql_db
    ports:
      - 8080:8080
    networks:
      - mynetwork


volumes:
  mongo_volume:
  postgresql_volume:  


networks:
  mynetwork:
    driver: bridge
