# mongod.conf

# Where to store the data
storage:
  dbPath: /data/db

# Network interfaces
net:
  bindIp: 0.0.0.0  # Bind to all IP addresses
  port: 27017

# Security settings
security:
  authorization: "enabled"  # Enable authentication

# System Log
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log
